apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: django-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "django"
        static_configs:
          - targets: ["django:8000"]
