apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: django-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==  
  MYSQL_DATABASE: bXlkYXRhYmFzZQ==  
  MYSQL_USER: bXl1c2Vy 
  MYSQL_PASSWORD: bXlwYXNzd29yZA==  
